name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 91.108.107.46
          username: u683493491
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "."
          target: /home/u683493491/domains/synapsehealthtech.com/public_html
          strip_components: 1
          rm: false
